EXAMPLES: list[dict] = [
    # ── Tier 1: simple facts, translations, reformatting ──────────────────────
    {"prompt": "What is the capital of France?", "tier": 1},
    {"prompt": "Translate 'good morning' to Spanish.", "tier": 1},
    {"prompt": "Convert 100 Fahrenheit to Celsius.", "tier": 1},
    {"prompt": "What does HTTP stand for?", "tier": 1},
    {"prompt": "Reformat this date: 06/20/2026 → June 20, 2026.", "tier": 1},
    {"prompt": "What is the plural of 'octopus'?", "tier": 1},
    {"prompt": "Translate 'thank you' to Japanese.", "tier": 1},
    {"prompt": "How many days are in a leap year?", "tier": 1},
    {"prompt": "What is 17 multiplied by 8?", "tier": 1},
    {"prompt": "Convert this JSON to YAML: {\"name\": \"Alice\", \"age\": 30}.", "tier": 1},
    {"prompt": "What is the chemical symbol for gold?", "tier": 1},
    {"prompt": "How many seconds are in an hour?", "tier": 1},
    {"prompt": "Translate 'cat' to French.", "tier": 1},
    {"prompt": "What is the square root of 144?", "tier": 1},
    {"prompt": "What country uses the currency 'yen'?", "tier": 1},
    {"prompt": "Convert 5 miles to kilometers.", "tier": 1},
    {"prompt": "What is the boiling point of water in Celsius?", "tier": 1},
    {"prompt": "Spell out the number 1,450 in words.", "tier": 1},
    {"prompt": "What does RAM stand for?", "tier": 1},
    {"prompt": "Translate 'hello' to Mandarin Chinese (pinyin).", "tier": 1},
    {"prompt": "What is the ISO code for the United States?", "tier": 1},
    {"prompt": "How many sides does a hexagon have?", "tier": 1},
    {"prompt": "What is 15% of 200?", "tier": 1},
    {"prompt": "Convert 2.5 kilograms to pounds.", "tier": 1},
    {"prompt": "What is the largest planet in the solar system?", "tier": 1},
    {"prompt": "Translate 'where is the bathroom?' to German.", "tier": 1},
    {"prompt": "What does URL stand for?", "tier": 1},
    {"prompt": "Format this phone number: 4155552671 → (415) 555-2671.", "tier": 1},
    {"prompt": "What year did World War II end?", "tier": 1},
    {"prompt": "What is the atomic number of carbon?", "tier": 1},
    {"prompt": "How many ounces are in a pound?", "tier": 1},
    {"prompt": "What color do you get mixing red and blue?", "tier": 1},
    {"prompt": "Translate 'I love you' to Italian.", "tier": 1},
    {"prompt": "What is the speed of light in km/s (rounded)?", "tier": 1},
    {"prompt": "What does CSS stand for?", "tier": 1},
    {"prompt": "Convert 0°C to Fahrenheit.", "tier": 1},
    {"prompt": "What is the capital of Japan?", "tier": 1},
    {"prompt": "How many bytes are in a kilobyte?", "tier": 1},
    {"prompt": "What is the Roman numeral for 9?", "tier": 1},
    {"prompt": "Translate 'goodbye' to Portuguese.", "tier": 1},
    {"prompt": "What is the tallest mountain in the world?", "tier": 1},
    {"prompt": "What does DNA stand for?", "tier": 1},
    {"prompt": "Convert 1 liter to milliliters.", "tier": 1},
    {"prompt": "What is 2 to the power of 10?", "tier": 1},
    {"prompt": "What language is spoken in Brazil?", "tier": 1},
    {"prompt": "Reformat: 'smith, john' → 'John Smith'.", "tier": 1},
    {"prompt": "What is the currency of the United Kingdom?", "tier": 1},
    {"prompt": "How many degrees are in a right angle?", "tier": 1},
    {"prompt": "What does API stand for?", "tier": 1},
    {"prompt": "Translate 'water' to Arabic.", "tier": 1},
    {"prompt": "What is the capital of Australia?", "tier": 1},
    {"prompt": "What is 1000 divided by 8?", "tier": 1},
    {"prompt": "Convert 30 minutes to seconds.", "tier": 1},
    {"prompt": "What element has the symbol 'Fe'?", "tier": 1},
    {"prompt": "Translate 'book' to Russian.", "tier": 1},
    {"prompt": "What is the smallest prime number?", "tier": 1},
    {"prompt": "How many continents are there?", "tier": 1},
    {"prompt": "What does SQL stand for?", "tier": 1},
    {"prompt": "Convert 100 meters to feet (rounded to one decimal).", "tier": 1},
    {"prompt": "What is the capital of Canada?", "tier": 1},
    {"prompt": "What is the next prime after 7?", "tier": 1},
    {"prompt": "Translate 'yes' to Korean.", "tier": 1},
    {"prompt": "How many hours are in a week?", "tier": 1},
    {"prompt": "What does GUI stand for?", "tier": 1},
    {"prompt": "What is the freezing point of water in Fahrenheit?", "tier": 1},
    {"prompt": "Reformat ISO date 2026-06-20 as DD/MM/YYYY.", "tier": 1},
    {"prompt": "What is the currency of Japan?", "tier": 1},
    {"prompt": "How many planets are in the solar system?", "tier": 1},
    {"prompt": "What does LLM stand for in machine learning?", "tier": 1},
    {"prompt": "Translate 'open' to Dutch.", "tier": 1},
    {"prompt": "What is 9 squared?", "tier": 1},

    # ── Tier 2: summarization, classification, structured analysis ─────────────
    {"prompt": "Summarize the following news article in three bullet points.", "tier": 2},
    {"prompt": "Classify this customer review as positive, negative, or neutral.", "tier": 2},
    {"prompt": "Extract all action items from this meeting transcript.", "tier": 2},
    {"prompt": "Summarize the key differences between REST and GraphQL.", "tier": 2},
    {"prompt": "Given this resume, list the candidate's top five technical skills.", "tier": 2},
    {"prompt": "Categorize these 20 support tickets by issue type.", "tier": 2},
    {"prompt": "Summarize this research paper's methodology and findings.", "tier": 2},
    {"prompt": "Identify the sentiment trend across these five product reviews.", "tier": 2},
    {"prompt": "List the pros and cons of remote work based on this article.", "tier": 2},
    {"prompt": "Parse this job description and output required vs. preferred qualifications.", "tier": 2},
    {"prompt": "Classify each of these emails as spam or not spam.", "tier": 2},
    {"prompt": "Extract the names, dates, and locations mentioned in this news story.", "tier": 2},
    {"prompt": "Summarize this legal contract in plain English.", "tier": 2},
    {"prompt": "Identify the main argument and supporting points in this op-ed.", "tier": 2},
    {"prompt": "Group these 15 product features into logical categories.", "tier": 2},
    {"prompt": "Summarize the differences between Python 2 and Python 3.", "tier": 2},
    {"prompt": "Given these five user stories, identify which are duplicates.", "tier": 2},
    {"prompt": "Extract all monetary values and their context from this financial report.", "tier": 2},
    {"prompt": "Classify each bug report as critical, major, or minor.", "tier": 2},
    {"prompt": "Summarize this 10-page policy document into an executive summary.", "tier": 2},
    {"prompt": "List the ingredients and steps separately from this recipe description.", "tier": 2},
    {"prompt": "Identify the tone (formal, informal, persuasive) of each paragraph.", "tier": 2},
    {"prompt": "Summarize what changed between version 1.0 and 2.0 of this changelog.", "tier": 2},
    {"prompt": "Tag each sentence in this support chat as question, answer, or complaint.", "tier": 2},
    {"prompt": "Extract all API endpoints mentioned in this technical document.", "tier": 2},
    {"prompt": "Compare and contrast the two product plans described in this brochure.", "tier": 2},
    {"prompt": "Summarize this 30-minute podcast transcript in five sentences.", "tier": 2},
    {"prompt": "Identify all dates and deadlines mentioned in this project brief.", "tier": 2},
    {"prompt": "Classify each news headline as politics, sports, technology, or entertainment.", "tier": 2},
    {"prompt": "Extract the key performance indicators from this quarterly report.", "tier": 2},
    {"prompt": "Summarize the patient's medical history from these clinical notes.", "tier": 2},
    {"prompt": "List the assumptions and constraints stated in this requirements document.", "tier": 2},
    {"prompt": "Identify which user feedback items relate to performance vs. usability.", "tier": 2},
    {"prompt": "Summarize the plot of this short story in two paragraphs.", "tier": 2},
    {"prompt": "Extract all named organizations from this press release.", "tier": 2},
    {"prompt": "Classify each transaction as income, expense, or transfer.", "tier": 2},
    {"prompt": "Summarize the arguments for and against this proposed legislation.", "tier": 2},
    {"prompt": "Identify any contradictions between these two policy documents.", "tier": 2},
    {"prompt": "List the open questions raised but not answered in this design doc.", "tier": 2},
    {"prompt": "Summarize this customer interview into a set of key insights.", "tier": 2},
    {"prompt": "Classify each code comment as explanatory, TODO, or outdated.", "tier": 2},
    {"prompt": "Extract the timeline of events from this incident report.", "tier": 2},
    {"prompt": "Compare the pricing models of the two SaaS products described.", "tier": 2},
    {"prompt": "Summarize the key takeaways from this conference talk abstract.", "tier": 2},
    {"prompt": "Identify which sections of this essay need more evidence.", "tier": 2},
    {"prompt": "Classify each dataset column as categorical, numerical, or datetime.", "tier": 2},
    {"prompt": "Summarize the feedback from these 10 employee performance reviews.", "tier": 2},
    {"prompt": "Extract all technical requirements from this client specification.", "tier": 2},
    {"prompt": "Identify the target audience implied by this marketing email.", "tier": 2},
    {"prompt": "Summarize the environmental impact assessment in this report.", "tier": 2},
    {"prompt": "List all the risks mentioned in this project plan.", "tier": 2},
    {"prompt": "Classify each social media post by its primary intent (inform, entertain, sell).", "tier": 2},
    {"prompt": "Extract all hyperlinks and their anchor text from this HTML snippet.", "tier": 2},
    {"prompt": "Summarize the competitive landscape described in this market analysis.", "tier": 2},
    {"prompt": "Identify the primary and secondary themes in this poem.", "tier": 2},
    {"prompt": "Group these error log entries by error type.", "tier": 2},
    {"prompt": "Summarize the setup instructions from this README into five steps.", "tier": 2},
    {"prompt": "Classify each interview response as technical, behavioral, or situational.", "tier": 2},
    {"prompt": "Extract the decision criteria used in this vendor evaluation document.", "tier": 2},
    {"prompt": "Summarize this academic abstract in language suitable for a general audience.", "tier": 2},
    {"prompt": "Identify which feature requests are in scope for the current sprint.", "tier": 2},
    {"prompt": "List the stakeholders and their roles mentioned in this project charter.", "tier": 2},
    {"prompt": "Classify each paragraph in this article as fact, opinion, or speculation.", "tier": 2},
    {"prompt": "Summarize the security vulnerabilities described in this audit report.", "tier": 2},
    {"prompt": "Extract all action verbs from these job responsibilities.", "tier": 2},
    {"prompt": "Identify the key metrics tracked in this analytics dashboard description.", "tier": 2},
    {"prompt": "Summarize the dietary guidelines from this nutrition document.", "tier": 2},
    {"prompt": "Group these customer complaints into recurring themes.", "tier": 2},
    {"prompt": "Classify each dataset record as valid, invalid, or needs review.", "tier": 2},
    {"prompt": "Summarize the findings from this A/B test report.", "tier": 2},

    # ── Tier 3: multi-step reasoning, argumentation, nuanced judgment ──────────
    {"prompt": "A company is deciding whether to rewrite its monolith in microservices. Analyze the trade-offs and recommend a strategy.", "tier": 3},
    {"prompt": "Given conflicting evidence in two studies, evaluate which conclusion is better supported and why.", "tier": 3},
    {"prompt": "A user's pull request improves performance but reduces readability. Should it be merged? Justify your decision.", "tier": 3},
    {"prompt": "Construct a counter-argument to the claim that AI will eliminate more jobs than it creates.", "tier": 3},
    {"prompt": "A startup has $50k runway and two possible pivots. Which should they pursue? Walk through the reasoning.", "tier": 3},
    {"prompt": "Explain why a sorting algorithm that is O(n log n) on average might still be slower than O(n²) in practice.", "tier": 3},
    {"prompt": "Evaluate the ethical implications of training a content moderation model on biased historical data.", "tier": 3},
    {"prompt": "A patient presents with three overlapping symptoms. What differential diagnoses should be considered and how would you triage?", "tier": 3},
    {"prompt": "Critique this policy proposal for universal basic income, addressing both its economic and social dimensions.", "tier": 3},
    {"prompt": "Two engineers disagree on database normalization vs. denormalization for a high-read workload. Mediate the debate with a recommendation.", "tier": 3},
    {"prompt": "A non-profit must cut 30% of its programs due to funding loss. How should it prioritize which to keep?", "tier": 3},
    {"prompt": "Explain how survivorship bias might distort conclusions drawn from startup success stories.", "tier": 3},
    {"prompt": "Should a self-driving car prioritize passenger safety over pedestrian safety in an unavoidable collision? Argue both sides.", "tier": 3},
    {"prompt": "A developer wants to use a GPL-licensed library in a commercial product. What are the legal and strategic considerations?", "tier": 3},
    {"prompt": "Evaluate whether this machine learning model's 94% accuracy is sufficient for deployment in a medical diagnosis context.", "tier": 3},
    {"prompt": "A city is considering banning single-use plastics. Analyze the environmental, economic, and social trade-offs.", "tier": 3},
    {"prompt": "Two candidates for a senior engineering role have complementary but non-overlapping strengths. How would you decide who to hire?", "tier": 3},
    {"prompt": "Explain why correlation does not imply causation, using a concrete example from public health data.", "tier": 3},
    {"prompt": "A SaaS company's churn rate increased after a UI redesign. Diagnose possible causes and suggest next steps.", "tier": 3},
    {"prompt": "Should an AI assistant refuse to answer questions about controversial historical events? Reason through the principles involved.", "tier": 3},
    {"prompt": "Analyze the long-term consequences of a country adopting a four-day work week nationally.", "tier": 3},
    {"prompt": "A team is split between adopting TypeScript now vs. migrating incrementally. Evaluate both approaches and recommend one.", "tier": 3},
    {"prompt": "Evaluate the fairness of using credit scores in hiring decisions, considering both employer and candidate perspectives.", "tier": 3},
    {"prompt": "A researcher's experiment has a p-value of 0.049. Should they claim statistical significance? Discuss the nuances.", "tier": 3},
    {"prompt": "Design an argument for why open-source AI models are more dangerous than proprietary ones, then steelman the opposing view.", "tier": 3},
    {"prompt": "An e-commerce site sees higher mobile traffic but lower mobile conversion. Diagnose the problem and propose solutions.", "tier": 3},
    {"prompt": "Evaluate whether a company should build or buy a data pipeline solution, given the described team size and timeline.", "tier": 3},
    {"prompt": "A journalist received leaked confidential documents exposing corporate fraud. Analyze the ethical considerations around publishing.", "tier": 3},
    {"prompt": "Explain how Goodhart's Law applies to performance reviews and propose a review system that mitigates it.", "tier": 3},
    {"prompt": "A government wants to mandate backdoors in encrypted messaging apps for law enforcement. Evaluate the security and civil liberties implications.", "tier": 3},
    {"prompt": "Diagnose why a microservices architecture might introduce more latency than the monolith it replaced.", "tier": 3},
    {"prompt": "An AI model performs well on benchmarks but poorly in production. What factors could explain this gap?", "tier": 3},
    {"prompt": "A school district must choose between tablets and laptops for students. Analyze the pedagogical and practical trade-offs.", "tier": 3},
    {"prompt": "Evaluate the argument that social media companies should be held liable for algorithmic amplification of misinformation.", "tier": 3},
    {"prompt": "A team discovered a critical bug two days before launch. Walk through how to reason about whether to delay or ship.", "tier": 3},
    {"prompt": "Explain the trolley problem and discuss how different ethical frameworks (utilitarian, deontological, virtue ethics) resolve it.", "tier": 3},
    {"prompt": "An investor must allocate between high-risk high-reward and low-risk stable assets in an uncertain market. Reason through the strategy.", "tier": 3},
    {"prompt": "Evaluate whether remote-first or hybrid-first is better for a 50-person software company, weighing culture, productivity, and hiring.", "tier": 3},
    {"prompt": "A city plans to replace a public park with affordable housing. Analyze the competing community interests and recommend a path forward.", "tier": 3},
    {"prompt": "Explain why adding more engineers to a late software project can make it later, using Brooks's Law.", "tier": 3},
    {"prompt": "Should an autonomous weapon system be allowed to make lethal decisions without human approval? Argue from multiple perspectives.", "tier": 3},
    {"prompt": "A product team has conflicting data: usability tests suggest one design, A/B tests suggest another. How should they decide?", "tier": 3},
    {"prompt": "Analyze whether a \"move fast and break things\" culture is appropriate for a fintech startup handling customer funds.", "tier": 3},
    {"prompt": "Evaluate the trade-offs between consistency and availability in a distributed system for a real-time messaging app.", "tier": 3},
    {"prompt": "A whistleblower faces retaliation for reporting safety violations. Analyze the ethical obligations of their employer and colleagues.", "tier": 3},
    {"prompt": "Explain how Dunning-Kruger effect and imposter syndrome can coexist on the same engineering team and how a manager should respond.", "tier": 3},
    {"prompt": "Evaluate whether the precautionary principle should govern the release of new gene-editing therapies.", "tier": 3},
    {"prompt": "A language model produces confident but factually wrong answers. Analyze the root causes and propose mitigation strategies.", "tier": 3},
    {"prompt": "An NGO is choosing between two interventions with similar expected outcomes but different variance in impact. How should they choose?", "tier": 3},
    {"prompt": "Should a platform moderate political speech differently from other content? Reason through the principles and practical implications.", "tier": 3},
    {"prompt": "A company's star engineer is also its most difficult team member. How should leadership balance productivity and team health?", "tier": 3},
    {"prompt": "Analyze how second-order effects could undermine a carbon tax policy that looks sound in first-order analysis.", "tier": 3},
    {"prompt": "Evaluate the argument that end-to-end testing should replace unit testing in a rapidly-changing codebase.", "tier": 3},
    {"prompt": "A biotech firm wants to patent a gene sequence. Analyze the ethical and legal dimensions from multiple stakeholder perspectives.", "tier": 3},
    {"prompt": "Reason through whether a recommender system optimizing for engagement is inherently at odds with user well-being.", "tier": 3},
    {"prompt": "A developing country must choose between building coal plants now or waiting for cheaper renewables. Analyze the dilemma.", "tier": 3},
    {"prompt": "Evaluate the claim that democratizing AI access increases overall safety compared to restricting it to large organizations.", "tier": 3},
    {"prompt": "An engineering team wants to adopt a new framework mid-project. Walk through how to evaluate the risk vs. reward.", "tier": 3},
    {"prompt": "Analyze how confirmation bias might affect the conclusions of an internal post-mortem after a major outage.", "tier": 3},
    {"prompt": "Should a news algorithm optimize for accuracy, engagement, or diversity of viewpoints? Reason through the trade-offs.", "tier": 3},
    {"prompt": "A founder must decide whether to take venture capital or remain bootstrapped. Walk through the key considerations.", "tier": 3},
    {"prompt": "Evaluate the long-term societal implications of widespread facial recognition technology in public spaces.", "tier": 3},
    {"prompt": "A healthcare provider wants to use an LLM for patient triage. Analyze the risks, benefits, and safeguards required.", "tier": 3},
    {"prompt": "Explain how principal-agent problems arise in corporate governance and what structural solutions exist.", "tier": 3},
    {"prompt": "A country is debating mandatory voting. Evaluate the democratic legitimacy arguments on both sides.", "tier": 3},
    {"prompt": "Reason through whether an AI trained exclusively on Western texts can fairly evaluate non-Western literature.", "tier": 3},
]
